apiVersion: apps/v1
kind: Deployment
metadata:
  name: danitag-deployment
  labels:
    app: dani
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dani
  template:
    metadata:
      labels:
        app: dani
    spec:
      containers:
      - name: dani
        image: danitag:v0
        ports:
        - containerPort: 3333
        - containerPort: 3333
          protocol: UDP
