apiVersion: v1
kind: Service
metadata:
  name: dani
spec:
  selector:
    app: dani
  ports:
    - port: 80
      name: tcp
      targetPort: 3333
      protocol: TCP
    - port: 90
      name: udp
      protocol: UDP
      targetPort: 3333
