apiVersion: v1
kind: Service
metadata:
  name: udp-echo
spec:
  selector:
    app: udp-echo
  ports:
    - port: 80
      name: tcp
      targetPort: 3333
      protocol: TCP
    - port: 90
      name: udp
      protocol: UDP
      targetPort: 3333
